### ISSUE TITLE
cqinclude rule - why this way

### ISSUE THREAD

**Issue by royteeuwen** [Adobe-Marketing-Cloud/aem-dialog-conversion#4]
Hello,

I am reviewing the code because we want to migrate from classic ui to granite ui / coral ui 3. What I have noticed and what is also stated in the documentation is that the cqinclude rule takes the destination path and adds those nodes to the source dialog and then subsequently rewrites them to granite ui.

Can you please explain me why it is done this way, and not just rewrite the cqinclude xtype to a granite/ui/components/coral/foundation/include resource type? We have like a bunch page components that all inherit from a base page where we have all the tabs organised in separate tab xmls, if we would do it this way, all the generic stuff would disappear and be duplicated over to all the page component dialogs. I would think there to be a better way of handling this? 

Greets,
Roy

**Comment by martinischeery** [comment]
Hi Roy,

This has been done to make sure that the converted dialog would be still working, given that the included component could still be in Classic UI (in such case, simply including it would lead to a broken dialog). We're now considering changing this, and as you proposed, keeping / converting the include component itself.  A ticket has been created to track this change internally.

Thanks,
Christian.

**Comment by royteeuwen** [comment]
Hey Christian,

Aha ok very nice to hear :)! Any estimation on a time schedule for such a change? We would like to start conversion in 2-3 months, but thats probably too optimistic ;)?

Greets
Roy

**Comment by martinischeery** [comment]
Hi,

We are currently working on other priorities so it would be quite challenging to provide you with a realistic estimate at the moment ;) 

However, since the code source is accessible, contributions are very welcome! In this case, the idea would be to simply replace the `IncludeRewrite` rule [0] with a content rule (cf. those defined in [1]).

Regards,
Christian.

[0] https://git.corp.adobe.com/CQ/dialog-conversion/blob/PRIVATE_master/bundles/cq-dialog-conversion/src/main/java/com/adobe/cq/dialogconversion/impl/rules/IncludeRewriteRule.java
[1] https://git.corp.adobe.com/CQ/dialog-conversion/tree/PRIVATE_master/content/jcr_root/libs/cq/dialogconversion/rules/classic

**Comment by royteeuwen** [comment]
Hey @martinischeery ,

Thanks, I will have definitely have a look at what we can do. The problem that would have to be overcome is that it would also have to convert the referenced xml. If the referenced xml is a dialog.xml then it's not that difficult because it will be converted by the tool, but if the referenced xml is for example a tab_basic.xml, just containing a specific tab, then it wont convert that one yet, will have to find a good way to do that :)

Greets
Roy

**Comment by pfauchere** [comment]
Closing as the issue is inactive
